//! Multi-family envelope profiles and routerd configuration generator.
//!
//! Provides matched speculative draft/primary model pairs and tier definitions
//! for supported model families: Qwen, Granite, Phi, and Gemma.

use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};

/// Supported setup model families.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SetupFamily {
    Qwen,
    Granite,
    Phi,
    Gemma,
    BitNet,
}

impl SetupFamily {
    pub fn parse(s: &str) -> Result<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "qwen" | "qwen2.5" => Ok(Self::Qwen),
            "granite" | "granite-3.0" | "granite3" => Ok(Self::Granite),
            "phi" | "phi-3.5" | "phi4" => Ok(Self::Phi),
            "gemma" | "gemma2" | "gemma3" | "gemma4" => Ok(Self::Gemma),
            "bitnet" | "bitnet-b1.58" | "ternary" => Ok(Self::BitNet),
            other => Err(anyhow!(
                "Invalid model family '{other}'. Supported: qwen, granite, phi, gemma, bitnet"
            )),
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Qwen => "qwen",
            Self::Granite => "granite",
            Self::Phi => "phi",
            Self::Gemma => "gemma",
            Self::BitNet => "bitnet",
        }
    }

    /// Primary GPU target model, CPU draft model, and optional reasoning model.
    pub fn matched_speculative_models(&self) -> (&'static str, &'static str, Option<&'static str>) {
        match self {
            Self::Qwen => ("qwen2.5:7b", "qwen2.5:0.5b", Some("deepseek-r1-distill-qwen:14b")),
            Self::Granite => ("granite-3.0:8b", "granite-3.0:1b", None),
            Self::Phi => ("phi-4:14b", "phi-3.5-mini:3.8b", Some("phi-4:14b")),
            Self::Gemma => ("gemma-2:9b", "gemma-2:2b", Some("gemma-2:27b")),
            Self::BitNet => ("bitnet:2b", "bitnet:2b", None),
        }
    }

    /// Generate `/etc/syntrop/routerd.toml` with matched speculative pairs and tiers.
    pub fn render_routerd_toml(&self, cpu_only: bool) -> String {
        let (primary, draft, reasoner) = self.matched_speculative_models();
        let fast_default = if cpu_only { draft } else { primary };
        let hard_default = if cpu_only { draft } else { reasoner.unwrap_or(primary) };

        let mut toml = format!(
            r#"# /etc/syntrop/routerd.toml
# Generated by `syn setup --family {}`

[daemon]
listen_tcp = "0.0.0.0:1982"
listen_unix = "/run/syntrop/router.sock"
varlink_socket = "/run/syntrop/io.syntrop.Router1"
inferenced_socket = "/run/syntrop/io.syntrop.Inference1"
log_level = "info"

[thresholds]
max_latency_ms = 15000
psi_memory_threshold = 25.0
max_retries = 2
rss_limit_mb = 15
min_tokens_per_second = 10.0

[tiers.fast]
name = "fast"
latency_weight = 0.60
cost_weight = 0.30
capability_weight = 0.10
default_model = "{fast_default}"

[tiers.hard]
name = "hard"
latency_weight = 0.15
cost_weight = 0.15
capability_weight = 0.70
default_model = "{hard_default}"

[[providers]]
id = "runtimed-local"
name = "Runtimed Owned Engine"
kind = "runtimed"
base_url = "/run/syntrop/io.syntrop.Runtime1"
tier = "fast"
weight = 1.3
enabled = true
timeout_ms = 600000

[[providers.models]]
name = "{draft}"
max_context_tokens = 32768
cost_per_input_token = 0.0
cost_per_output_token = 0.0
avg_latency_ms = 20.0
tokens_per_second = 250.0
tier = "fast"
"#,
            self.as_str()
        );

        if !cpu_only {
            toml.push_str(&format!(
                r#"
[[providers.models]]
name = "{primary}"
draft_model = "{draft}"
max_context_tokens = 32768
cost_per_input_token = 0.0
cost_per_output_token = 0.0
avg_latency_ms = 40.0
tokens_per_second = 300.0
tier = "fast"
"#
            ));
        }

        if let Some(r) = reasoner {
            if r != primary || cpu_only {
                toml.push_str(&format!(
                    r#"
[[providers.models]]
name = "{r}"
draft_model = "{draft}"
max_context_tokens = 32768
cost_per_input_token = 0.0
cost_per_output_token = 0.0
avg_latency_ms = 70.0
tokens_per_second = 120.0
tier = "hard"
"#
                ));
            }
        }

        if *self == Self::Gemma {
            toml.push_str(
                r#"
[[providers.models]]
name = "embeddinggemma:270m"
max_context_tokens = 8192
cost_per_input_token = 0.0
cost_per_output_token = 0.0
avg_latency_ms = 15.0
tokens_per_second = 500.0
tier = "fast"
"#,
            );
        }

        toml
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_family_parse_all_supported() {
        assert_eq!(SetupFamily::parse("qwen").unwrap(), SetupFamily::Qwen);
        assert_eq!(SetupFamily::parse("granite").unwrap(), SetupFamily::Granite);
        assert_eq!(SetupFamily::parse("phi").unwrap(), SetupFamily::Phi);
        assert_eq!(SetupFamily::parse("gemma").unwrap(), SetupFamily::Gemma);
        assert_eq!(SetupFamily::parse("bitnet").unwrap(), SetupFamily::BitNet);
        assert!(SetupFamily::parse("unknown_fam").is_err());
    }

    #[test]
    fn test_render_routerd_toml_speculative_pairs() {
        for fam in [SetupFamily::Qwen, SetupFamily::Granite, SetupFamily::Phi, SetupFamily::Gemma, SetupFamily::BitNet] {
            let toml = fam.render_routerd_toml(false);
            assert!(toml.contains("[tiers.fast]"));
            assert!(toml.contains("[tiers.hard]"));
            let (_, draft, _) = fam.matched_speculative_models();
            assert!(toml.contains(draft));
            assert!(toml.contains(&format!("draft_model = \"{draft}\"")));
        }
    }
}
