//! Generation and filesystem serialization of speculative routerd.toml configuration.

use std::fs;
use std::path::Path;

/// Detects whether current host is in a CPU-only hardware envelope (no discrete GPU VRAM).
pub fn detect_cpu_only_envelope() -> bool {
    detect_cpu_only_envelope_at(Path::new("/sys/class/drm"), Path::new("/dev"))
}

/// Detects envelope from specified sysfs and dev paths (allows test isolation).
pub fn detect_cpu_only_envelope_at(drm_dir: &Path, dev_dir: &Path) -> bool {
    if let Ok(val) = std::env::var("SYNTROP_HARDWARE_ENVELOPE") {
        let v = val.trim().to_ascii_lowercase();
        if v == "cpu" || v == "cpu-only" {
            return true;
        }
        if v == "gpu" || v == "cuda" {
            return false;
        }
    }
    if dev_dir.join("nvidia0").exists() || dev_dir.join("nvidiactl").exists() {
        return false;
    }
    if let Ok(entries) = fs::read_dir(drm_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with("card") && !name_str.contains('-') {
                let dev_path = entry.path().join("device");
                if let Ok(vendor) = fs::read_to_string(dev_path.join("vendor")) {
                    let v = vendor.trim().trim_start_matches("0x");
                    if v.eq_ignore_ascii_case("10de") {
                        return false;
                    }
                    if v.eq_ignore_ascii_case("1002") {
                        if let Ok(vram) = fs::read_to_string(dev_path.join("mem_info_vram_total")) {
                            if let Ok(bytes) = vram.trim().parse::<u64>() {
                                if bytes >= 3 * 1024 * 1024 * 1024 {
                                    return false; // Discrete AMD GPU (>= 3GB VRAM)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    true
}

/// Generates `/etc/syntrop/routerd.toml` with paired speculative sessions (`draft_model`)
/// and shared `Arc<VocabTrie>` pooling comments.
pub fn generate_speculative_routerd_toml(family: &str) -> String {
    generate_speculative_routerd_toml_envelope(family, detect_cpu_only_envelope())
}

/// Generates speculative router configuration with explicit CPU-only envelope gating.
pub fn generate_speculative_routerd_toml_envelope(family: &str, cpu_only: bool) -> String {
    let (primary, draft, reasoner) = match family {
        "granite" => ("granite-3.0:8b", "granite-3.0:1b", None),
        "qwen" => ("qwen2.5:7b", "qwen2.5:0.5b", Some("qwen2.5:14b")),
        _ => ("gemma-2:9b", "gemma-2:2b", Some("gemma-2:27b")),
    };

    let fast_default = if cpu_only { draft } else { primary };
    let hard_default = if cpu_only { draft } else { reasoner.unwrap_or(primary) };
    let reasoner_section = if let Some(r) = reasoner {
        format!(
            r#"
[[providers.models]]
name = "{r}"
draft_model = "{draft}"
max_context_tokens = 32768
cost_per_input_token = 0.0
cost_per_output_token = 0.0
avg_latency_ms = 80.0
tokens_per_second = 150.0
tier = "hard""#
        )
    } else {
        String::new()
    };

    format!(
        r#"# /etc/syntrop/routerd.toml
# Generated by `syn setup --family {family}`

[daemon]
listen_tcp = "0.0.0.0:8000"
listen_unix = "/run/syntrop/router.sock"
varlink_socket = "/run/syntrop/io.syntrop.Router1"
inferenced_socket = "/run/syntrop/io.syntrop.Inference1"
log_level = "info"

[thresholds]
max_latency_ms = 15000
psi_memory_threshold = 25.0
max_retries = 2
rss_limit_mb = 15
min_tokens_per_second = 10.0

[tiers.fast]
name = "fast"
latency_weight = 0.60
cost_weight = 0.30
capability_weight = 0.10
default_model = "{fast_default}"

[tiers.hard]
name = "hard"
latency_weight = 0.15
cost_weight = 0.15
capability_weight = 0.70
default_model = "{hard_default}"

# Provider: runtimed with paired speculative decoding and shared Arc<VocabTrie>
[[providers]]
id = "runtimed-local"
name = "Runtimed Owned Engine"
kind = "runtimed"
base_url = "/run/syntrop/io.syntrop.Runtime1"
tier = "fast"
weight = 1.3
enabled = true
timeout_ms = 600000

[[providers.models]]
name = "{primary}"
draft_model = "{draft}"
max_context_tokens = 16384
cost_per_input_token = 0.0
cost_per_output_token = 0.0
avg_latency_ms = 40.0
tokens_per_second = 300.0
tier = "fast"

[[providers.models]]
name = "{draft}"
max_context_tokens = 8192
cost_per_input_token = 0.0
cost_per_output_token = 0.0
avg_latency_ms = 15.0
tokens_per_second = 450.0
tier = "fast"{reasoner_section}
"#
    )
}

/// Atomically writes routerd.toml configuration file to disk.
pub fn write_routerd_config(path: &Path, content: &str, dry_run: bool) -> anyhow::Result<()> {
    println!(
        "\n[2/3] Writing speculative sessions to configuration: {}",
        path.display()
    );
    if dry_run {
        println!("  [dry-run] Configuration preview generated successfully.");
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    match fs::write(path, content) {
        Ok(_) => {
            println!("  [✓] Successfully saved {}", path.display());
            Ok(())
        }
        Err(e) => {
            eprintln!(
                "  [!] Notice: could not write to {} ({}). Please re-run with: sudo syn setup",
                path.display(),
                e
            );
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_speculative_routerd_toml_qwen() {
        let toml = generate_speculative_routerd_toml("qwen");
        assert!(toml.contains("name = \"qwen2.5:7b\""));
        assert!(toml.contains("draft_model = \"qwen2.5:0.5b\""));
        assert!(toml.contains("Arc<VocabTrie>"));
    }

    #[test]
    fn test_generate_speculative_routerd_toml_granite() {
        let toml = generate_speculative_routerd_toml("granite");
        assert!(toml.contains("name = \"granite-3.0:8b\""));
        assert!(toml.contains("draft_model = \"granite-3.0:1b\""));
    }

    #[test]
    fn test_generate_speculative_routerd_toml_gemma() {
        let toml = generate_speculative_routerd_toml("gemma");
        assert!(toml.contains("name = \"gemma-2:9b\""));
        assert!(toml.contains("draft_model = \"gemma-2:2b\""));
    }

    #[test]
    fn test_generate_speculative_routerd_toml_cpu_only() {
        let toml_cpu = generate_speculative_routerd_toml_envelope("qwen", true);
        assert!(toml_cpu.contains("default_model = \"qwen2.5:0.5b\""));
        let toml_gpu = generate_speculative_routerd_toml_envelope("qwen", false);
        assert!(toml_gpu.contains("default_model = \"qwen2.5:7b\""));
        assert!(toml_gpu.contains("default_model = \"qwen2.5:14b\""));
    }

    #[test]
    fn test_detect_envelope_amd_apu_vs_dgpu() {
        let temp = tempfile::tempdir().unwrap();
        let drm_apu = temp.path().join("drm_apu");
        let dev = temp.path().join("dev");
        let apu_card = drm_apu.join("card0").join("device");
        std::fs::create_dir_all(&apu_card).unwrap();
        std::fs::create_dir_all(&dev).unwrap();
        std::fs::write(apu_card.join("vendor"), "0x1002\n").unwrap();
        std::fs::write(apu_card.join("mem_info_vram_total"), "536870912\n").unwrap();
        assert!(detect_cpu_only_envelope_at(&drm_apu, &dev));

        let drm_dgpu = temp.path().join("drm_dgpu");
        let dgpu_card = drm_dgpu.join("card0").join("device");
        std::fs::create_dir_all(&dgpu_card).unwrap();
        std::fs::write(dgpu_card.join("vendor"), "0x1002\n").unwrap();
        std::fs::write(dgpu_card.join("mem_info_vram_total"), "8589934592\n").unwrap();
        assert!(!detect_cpu_only_envelope_at(&drm_dgpu, &dev));
    }
}
