d /run/syntrop 0775 root syntrop -
d /run/systemd-sentry 0775 sentry syntrop -
d /var/lib/syntrop 0775 syntrop syntrop -
L+ /run/syntrop/io.syntrop.Sensory1 - - - - io.syntrop.Runtime1
L+ /run/syntrop/io.syntrop.Actuator1 - - - - io.syntrop.Tool1
L+ /run/syntrop/io.syntrop.Telemetry1 - - - - io.syntrop.Inference1

